# -*- mode: ruby -*-
# vi: set ft=ruby :

unless ENV['PHANTOMJS_REPO']
  ENV['PHANTOMJS_REPO'] = 'https://github.com/tinfoil/phantomjs.git'
  puts "No PHANTOMJS_REPO environment variable detected. Defaulting to #{ENV['PHANTOMJS_REPO']}"
end

unless ENV['PHANTOMJS_VERSION']
  ENV['PHANTOMJS_VERSION'] = 'master'
  puts "No PHANTOMJS_VERSION environment variable detected. Defaulting to #{ENV['PHANTOMJS_VERSION']}"
end

Vagrant.configure("2") do |config|
  config.vm.define :precise64 do |c|
    c.vm.box_url = "http://files.vagrantup.com/precise64.box"
    c.vm.box     = "precise64"
  end

  config.vm.provision :shell, path: "provision-vm.sh" do |s|
    s.args = [
      ENV['PHANTOMJS_REPO'],
      ENV['PHANTOMJS_VERSION']
    ]
  end

  # You may wish to tweak these, but be aware that you need quite a lot of
  # memory for the linking stage.
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 3072]
    vb.customize ["modifyvm", :id, "--cpus",   2]
  end
end
